name: ci

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - 'VERSION'
    branches: 
      - main

jobs:
  ci:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10'] # TODO: '3.11-dev'
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: '**/*requirements.txt'
      - name: Install dependencies
        run: |
          pip install lume
          lume -install
      - name: Lint
        run: lume -lint
      - name: Check Requirements
        run: lume -check-requirements
#      - name: Static Analysis
#        run: lume -static-analysis
      - name: Tests
        run: lume -build -test
      - uses: codecov/codecov-action@v2
        with:
          files: output/coverage/cobertura_coverage.xml
          name: gradgpad
          fail_ci_if_error: true
      - name: Check Installation (--no-binary)
        run: |
          pip install wheel
          python setup.py sdist
          pip wheel --no-binary gradgpad -w /tmp/ext dist/gradgpad-*.tar.gz
      - name: Check Installation (temporary)
        run: pip install gradgpad