name: Reproducible Research

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - 'VERSION'
    branches: 
      - main

jobs:
  reproducible_research:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: ['3.11']
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: '**/*requirements.txt'
      - name: Install Package
        run: pip install -e .
      - name: Execute Reproducible research
        run: gradgpad --reproducible-research -o reproducible_research